routes and ts migrate
CrossJV/React-cinema pull request #5
Opened 2024-03-01 23:04 UTC by CrossJV

2024-03-05 19:44 UTC, Levitinn requested changes

2024-03-05 19:44 UTC, Levitinn commented on src/hooks/useAuth.tsx
>  	const {0: user, 1: setUser} = useState('');
это что за стейт такой?))
нужно переделать, используй либо объект либо массив, либо просто значение.

2024-03-05 19:44 UTC, Levitinn commented on src/contexts/user.context.tsx
> +	const {0: user, 1: setUser} = useAuth();
и тут не понятный стейт.

2024-03-05 19:44 UTC, Levitinn commented on src/pages/Auth/Auth.tsx
>  	const {0: userName, 1: setUserName} = useState('');
и здесь он же. разберись. он должен быть в одном месте и прокидываться туда где нужен

2024-03-06 22:29 UTC, CrossJV commented on src/pages/Auth/Auth.tsx
>  	const {0: userName, 1: setUserName} = useState('');
Этот стейт относится к инпуту куда мы вбиваем логин для входа, что с ним не так, можете пояснить?

2024-03-06 22:30 UTC, CrossJV commented on src/hooks/useAuth.tsx
>  	const {0: user, 1: setUser} = useState('');
Вы имеете в виду переделать этот хук без стейта? или в самом стейте использовать иное значение начальное нежели пустую строку?

2024-03-10 18:47 UTC, Levitinn commented on src/hooks/useAuth.tsx
>  	const {0: user, 1: setUser} = useState('');
да, прости, действительно не до конца описал свой вопрос.
Мне интересно, почему ты создаешь состояние через такой синтаксис `const {0: user, 1: setUser} = useState('');`?
Почему не используешь стандартную запись `const [user, setUser] = useState('');`

2024-03-10 20:43 UTC, CrossJV commented on src/hooks/useAuth.tsx
>  	const {0: user, 1: setUser} = useState('');
Потому что когда мы создаем стейт через [] у нас создается итератор, который на мой взгляд тут вообще не нужен, в следствии этого у нас больший расход по памяти и меньше быстродействие, прикладываю спецификацию. https://tc39.es/ecma262/#prod-ArrayAssignmentPattern. Если надо, могу всё конечно переделать на массивные скобки

2024-03-11 19:53 UTC, Levitinn commented on src/hooks/useAuth.tsx
>  	const {0: user, 1: setUser} = useState('');
затраты памяти на итерацию по двум элементам ничтожно мала для данной операции, и уж тем более для проекта в целом,. Однако, ты добавляешь значительное неудобства используя нестандартный подход.
Ты делаешь 
- менее читабельный код 
- нестандартный подход для базовой операции
- при использовании объекта при деструктуризации ты не можешь явно указать тип данных для стейта.
Не стоит использовать такой подход ни в каких случаях

2024-03-13 18:11 UTC, Levitinn requested changes
нужно сделать роуты для отображения фильма. по клику на фильм открывать страницу фильма

2024-03-17 18:39 UTC, merged