auth layout
CrossJV/React-cinema pull request #6
Opened 2024-03-17 18:40 UTC by CrossJV

2024-03-19 20:19 UTC, Levitinn requested changes
![image](https://github.com/CrossJV/React-cinema/assets/44999446/9cfacc91-9db0-4894-88f4-b08349e1b3b1)
проект не поднимается

2024-03-20 19:53 UTC, Levitinn requested changes
у меня не получается никуда перейти кроме авторизации, и после нажатия "войти в профиль" поле очищается, но ничего не происходит

2024-03-20 20:08 UTC, CrossJV commented
в локал сторадже должно быть поле users с данным, например вот такими

[{"name":"Vasya","isLogined":false},{"name":"Phill","isLogined":false},{"name":"Andrew","isLogined":false},{"name":"Helen","isLogined":false},{"name":"Jack","isLogined":false},{"name":"Ann","isLogined":false},{"name":"Bill","isLogined":false}]

2024-03-21 19:47 UTC, Levitinn requested changes

2024-03-21 19:47 UTC, Levitinn commented on src/pages/Main/Main.tsx
> +			const { data } = await axios.get(`https://search.imdbot.workers.dev/?q=${evt.target.search.value}`);
раз уж у тебя есть отдельный компонент для рендера фильмов FilmList, то логично вынести загрузку фильмов в него. Потому что именно он за фильмы и отвечает, а в мейн логика касаемая фильмов - ни к чему.

2024-03-21 19:47 UTC, Levitinn commented on src/pages/Main/Main.tsx
> +	const getFilms = async (evt: BaseSyntheticEvent) => {
при переходе на страницу фильмов, отображается, что фильмов нет. и запрос за фильмами не уходит. стоит выводить какие то фильмы и без поиска. Хотя и с поиском у меня запросы падают

2024-03-25 09:44 UTC, Levitinn requested changes
у меня по прежнему все запросы к апи падают. попробуй все таки найти какое то другое апи

2024-03-25 09:44 UTC, Levitinn commented on src/components/FilmList/FilmList.tsx
> +			setFilms && setFilms(data.description);
лишняя проверка на setFilms. а вот на то что в ответе что то пришло, проверять стоит

2024-03-26 07:46 UTC, CrossJV commented on src/components/FilmList/FilmList.tsx
> +			setFilms && setFilms(data.description);
ругается тс, поэтому добавил

2024-03-26 19:47 UTC, Levitinn commented on src/components/FilmList/FilmList.tsx
> +			setFilms && setFilms(data.description);
тс ругается потому что здесь у тебя этот метод стоит как необязательный 
![image](https://github.com/CrossJV/React-cinema/assets/44999446/06e2b848-83e3-4132-ac56-01a5d1e90d49)
но ведь он основной, убери вопросительный знак и можно будет убрать проверку

2024-03-26 19:48 UTC, Levitinn approved these changes
молодец. один комментарий. исправь со след заданием

2024-03-26 20:11 UTC, merged